---
apiVersion: v1
kind: Secret
metadata:
  name: myrouter
  labels:
    application: messaging
type: Opaque
stringData:
  connect.json: |-
    {
        "scheme": "amqp",
        "host": "messaging"
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: icproxy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: icproxy-view
subjects:
- kind: ServiceAccount
  name: icproxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
