apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skuppman-sku-pacman
  labels:
    name: pacman
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: skuppman
subjects:
- kind: ServiceAccount
  name: pacman
  namespace: sku-pacman
