apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: skuppman
  labels:
    name: pacman
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - watch
  - list
