---
kind: ConfigMap
metadata:
  name: qdr-config
apiVersion: v1
data:
  qdrouterd.conf: |
    router {
       id:west-2
       mode: interior
    }

    sslProfile {
       name:ssl-profile
       certFile: /etc/qpid-dispatch-certs/internal/tls.crt
       keyFile:/etc/qpid-dispatch-certs/internal/tls.key
       passwordFile: /etc/qpid-dispatch-certs/internal/tls.pw
       caCertFile: /etc/qpid-dispatch-certs/internal/ca.crt
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: amqp
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: 8672
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
       http: yes
    }

    listener {
       sslProfile: ssl-profile
       role: inter-router
       host: 0.0.0.0
       port: 55672
       saslMechanisms: EXTERNAL
       authenticatePeer:yes
    }

    address {
       prefix: closest
       distribution: closest
    } 

    address {
       prefix: multicast
       distribution: multicast
    }
