apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZkekNDQTE4Q0ZDZ0d3dHh0Q3VONGRiL2FKZ1Z0Ty9MUzZkM2ZNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1HUXgKQ3pBSkJnTlZCQVlUQWxWVE1SRXdEd1lEVlFRSURBaE9aWGNnV1c5eWF6RVJNQThHQTFVRUJ3d0lRbkp2YjJ0cwplVzR4RmpBVUJnTlZCQW9NRFZSeWRYTjBJRTFsSUVsdVl5NHhGekFWQmdOVkJBTU1EbFJ5ZFhOMFpXUXVRMEV1ClkyOXRNQjRYRFRFNU1EZ3lNVEUyTlRBd00xb1hEVFEzTURFd05URTJOVEF3TTFvd2dZc3hDekFKQmdOVkJBWVQKQWxWVE1Rc3dDUVlEVlFRSURBSkRRVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RVZNQk1HQTFVRQpDZ3dNVW1Wa0lFaGhkQ0JKYm1NdU1VQXdQZ1lEVlFRREREZHBiblJsY2kxeWIzVjBaWEl0WkdWdGJ6SXRZVzF4CkxtRndjSE11YzNWdGJXbDBMbk41YzJSbGMyVnVaeTFsWVhOMExURXVZMjl0TUlJQ0lqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBbmRQcW16b04zZEIvSVBWczVuQzBDMlVONkdwWUFVSDdKZmVIbVM2RgpYVHBqVVUzL3dUZkl5a01GVGVNQ2YzV2FPZTAvNjNjMWV5RndXT3EvL1RTdTEwbGFQS0dzVVJPbzZSS1ZyVWtECjVmbWQranR3ckJxVk1ZQy9jODNjRDVLUjh5UHo0ZFpGUGw3RHhsYVgwRGQ3NmVxc1YvRndvTytNTGV0dWJ1YmMKVDA2ai94bzcyWFhuVHgxbTE0V1UwWUJtbFB1Z20zOFk3cXlvWjRWcUZuMFZjRy9LcEJNd3JPTzVDc1NKc1JHNwpJR2VTYU96RFN2RDFiNERCbUlKN3pnd05WelMrc0orODkwK1dYa3pmY0d3SkdqY0tjUWlYTjJNMExEbzUySHFUCkF6OWdlbmEzV1J6U0QwbWVKK3RFL2lsdzFSdXJrOXRnaDNUWXZ0RVpQWEhqWWZKL1o0SC9MNWxUdGZkL1U2SHcKU1crK1RialVyaGNNOGNpL2RXTXowdnJScVZCeWhCTU1aZ0Nzck01UkgrNjkyTnYzNHRCbytxU2FWRERPbEtMWApVQ0VqWDRNTGR1UG1nbVJYYk5abmR3TjFnSi8wcUEvdHRWK2R3TXAyNmZKRU9uYWhENmtmTHBhNXpCQjhIdXpqCnZ3UThuQ1RQaDdtSWZJYk9FdHY3TlJOaW1ld1Y4RzlFL3BFK29lWGx3ZUE0NWkzOVdnK2tsWEdyNlVlMVh4UFEKZWRkeFkxNXpRMlJWaXVxMDg3OWgzbEF1TFU2aTBzbG5iSDFxaDVtRFNmREdSY1pqNjNTbWNHa2dDM0hmQlRQUApFVjlwR21hQkRxejF2bmRpRDc4K04rbkJWeDc1Y2RYVFFqTHhsQlZac2hDZVg5aGZXNlR1a1YrenRocjIrd1Z2CkxlMENBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQWhJN2FEVmRoUlpVSHFUNmV5M2dTcFEvUmNBY1YKS0ZkTCtJZGFSTkNZVTlia1ZBamo5N0YyTWdTZlFjT21wMzVISzEvVS9va2x0RGEyQUJtQU1GZm1RWk1hZTMvNQplRHJ5ak45QWpGV09mOWd3a1UvdWlweXEvbGViS3phSTNaV1Z4dFdGZ1NSeENad2xYak83N0pOTjBEa1FveHlDCm9PS3RlVWU5WlMydDVHVFpZVXdyNGVQZFVKR1V5S25nOFFHZERZeWZsZzYrbVJlS0pFU3NXOFdDOVRndWFLQUgKaU5zVlhDK2tHRzBqWDVrZlE0andvL2ZVYXRHNGhmRlVlWUEzdzYxYlozTzBTMGk4YjlYd0tJd3MydXNQQkFmNgpLV21tcjBBaElwemMwcDJkR3dyaXJ1dnpMcERCVUwzbUNIakFSK09UbXFSWHpDYTBxSUFOSTV1Y2VoeWhVeU1CCnhkNTNoUmdxT2xLTkR4bEc3cDBLVXR6dE9LWUZLcDBURmkzaGpNYmp4enRzbzF4ZUhxdjBEUDQxYlBxdG1OUWEKWXc4eGxPck1kbUxFQ3Y5VmZJeXh1M0YxRUUyeTBZMTRBaVp1Y1BlOVd6U245NmcrSTFzSjIyYVFhWE1nNjhkSwoxM3BlTWZLczYrdCtLQUJLZW10K2ExSk5IZ0QwRUpDdEF0MWt6N01OZVprSFlJSkpNb1lQVTFxczlzWFpSaXh1Cjh0MG9oZkFwQ0JoMjM0UUxYZUxuT2xWNHlLcGR3V2RFQkZId2lJVENDd3dJVXZVWWUxZ2lkclg5OFgya1U3V0QKTGRWeVJrS3dvWElXMU9acUhWZEgzWUx2NndsYWkwa0tVcmYxSDZXK0hYMUlnUmFsMWl4a2hMTXdxQXFucHkwTApaVUJManlpekUrdlpBQzg9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMjU2LUNCQywzQjAwQUJGNjMzOTUxM0FBQjExOUU1QUY4MjQ1RTQ3OAoKWURtNE1GcktodHpnamgzWEV2dENjeWNoLzBUOTZKb0gvcWpSTHFrMS91VktQOFRHRWdLd3AvZ3A4M1BVMGVOSQp2R0pRZVRrSm9SZzhWblRGMnpOQU82c2NYMEhHQmI0aTliYlNxTWo3cFpRb2hlYWZDYmNwL0FkcnFHTjdqMjFhCjZ4dUg5SnNDYWM2dy9IYTB3emxjZFMwRHI4UlNOUURITjk0VlFTQVVRZGUwMG1QUHBhdFd4ODhka25qeEhqNWkKdzZnTE83MFJDWGY4UDlYYlJ6aDBvZE5PUVZhVnMyNHlHMzR2MWE4Tng0Z0d5ZXFzS0VjOFNFRnpKTlpYSkhXTAo0QVVyalFMYkswNFhIVGpDMkNYeWdja0R1bFhGYkdHdG1kbDBpQlE5VmtQMXhINGhWV1Q5anMrQUJMU29NR0FOCkh6YmltMnlUb0lhT2Rna1A1SGN6b1lEd3hSZzlabEIvYXZQbSt0bFltVWhyTEF6SUNVTC9SV0FISEQzN3FwRVYKV0I3YkhKZTBaajIwZWtzL21mTzI0Qm8xWVNzSUhHWXhva0M2VUtKZVlaQ1MxVmhKdEtXN1RTTUZGQllnYXpHbgp6NHhHTEl5RjFYZHMzcjRpTkg2M1RNaThROTRmU1VQUHZTeFV1d2N6R3pkOTVGNlowUG9HTkw4TkRGVjRKdzVwCkEzMTNoRkdiV1RXMkZ5Und6ajJYKzIzM3VsNGV1SmxUWnJCbTEzdWRpRWwwakIrWnBUbERSQTlhV0NOT3EyajgKQ1A2YmlycXI1eWZteXBucUJOalFLS0h5Y3A0T2c1NXZYandhV1Rlbk44N0M4NmdWbS9JMXNhYlc1S0JiL0dwdApjZGJlNldlZ1UwcUtzV0h5NHpCYzlaa2hwaDlEdVg5dnJNOTdsMjZicG5LMFVKWHQveWR6VmtMSVhyMEV3OEVPCkdWbzZnc0IrNEhtMi9nNXlGRTRzODUzNStMVEhibmFPcmNKcXJOanc4SDBLTzlBR2ZwZWNKRnN6cWVVSk5YWUEKM2tIZVpmRG5DaC9FVXJxR0FtUWE4cjV6bWc0eW5XcTdhOHBTdWdTZlJxWWVsSVZZZjg5RklmbXg4NExjRnFIZQpMU3B6T29TMGovWU4wTEtyNGlGM2VUVHVxczlycUQ2L0R1Q1VvUUs1M3NTLzE1a1JmYjdVS1p6RUp0MW9MSE1MCkxGc2V5RkkrWXpaakw5ZUE0Z2QxTHh3a3cza1pyVmdPVG5CZkFFN3hOWXh4WkErcmpWbWwzUjhVd3BWdWYyZXQKRXZQNlQzS2VNTUFXbnBPNk55Y05oSURBU1BIdndEY1gvdjRYYWszaWw0WHY1cnViMGtJaWIxK3YvMHpFa1FpYQphWlMxZ29ZYmRNWkhJcnRkakdWVG1XcmwyM1BrMHZNWEZuQmd4Qkk4NFJxY1FYdTV0cE1IamlzZk4wSDU0dDZlCk8xSjkrT1Y2ZVJhNklpS3I1TWgwU0NQdzFEdFZUVHhGOGNKR29rWHQzc3BZM1lKc3U2cHBLTXdLUnExaWVoeVQKYW5DUzkxbStFTHAxSWdBbGx2Ryt2ZVNVbWJkWmZwaXk2N0JPd0ZyeXZsdEcrVUpETEJSMEVMek4vUFVTangxTgpuTWoyeHNUK0ZtVTl3YzZsdzVEQ0dHUWF4UUxXUFUzbGFTcGEwQWJ0NVNBc0FnbnkrNmZzN01lYVRIZ0N3UjhzCnFDZldvU05IMFZCZXFoaFdCQ3VmRitMRitqcDVsS3UrTytmYjhnSjdFcUhQTWc3cStValRkWmsvcDl1RTI4UkkKYWppTkVxeDRUTnZRV2c3VldlQWw4MWhFNmlQTmlZUlNtTk95NUhFdkErcUlKWm5BYzlRREdWTmhFNUFVTE11ZgpIa0FmOHlkbXFvTnV4Z3ZhTWJGK3RMVms3ZTBTUFg5SDBWQjc5ODBqZjZ3emtVWmdLd080YkVIaDdQQ1F1REtwCnlvUEdHMmltQnh3SUNIMVlFWWN6dG5DdENZeWw1T3NyWEExcGNoVytxZU9PeFNvTnpPYTZycitSUThMSEdQVGkKM1lzQlUwOER3QWxjdHUxR054MmVObU5HQVYvcHhPaE80VzNGTkNWSkowYzBlcXUrTXUzVkRVaGVCR2NhTG9JNQplQ2RWcVJRQ1N1Q29WNEcvTm9OY0Ntc056NUJmd2puWkxEMDliZ0NyTTdqQ0U5R3FhMlM4OXBIWnl4ejg2QTViCmgwSTNVMjBYUndwYitNejNiQ01IOTdBUmFyMjhkSUd1ZGVNR2w5YUM3Mzl3eU5IVnpVbmtMcHduRS9OSlprNU0KVlE0TW04OGFQdFFwWGNrb3VTN2p2bWpVRVJTTk4weE1vUGhFUXB5Zk1ZTXRaQXBhODNFUTRPRm9oV0pFeVlhTgpJYS9SUTlua3UyNVBWZUN0dUVjU2x2ZGptZXpoV0tFRWd5aW5sRTFEejFqZWJhK25RZU5kN28vR1NxVWx2a09YCmNwZXNXMFVCZjFSVCtXMnBadHdiRUJNa2RPVE4zenN1YTBmemNXZDZNMXh4NXNtdTlJRy80U2ZBOURWd21LS1cKQVFMbURwTUlkRk10OWtQNEY5UndEZ0tXcGw1WGFmM1RRMjVGamZvczZ5Z1I1cXdWZXRDUXF0Wkh2TXozYklBQQprcW5vRFFEaGNXdEFJbVFqcjJkb3FYUXpWa2JXVDRRbDI0Z1hFdFZ6SnhyOFRodllTaHZtNnJ6UHVMWFJXWE9nCmNZbm5UVURnQmJrZGpzS1l2Z3QxV1Z4TGZHT0ZXM2VtbzRyOVBrUTBaVmxlcFZlamZlUmpUMmJCZVlUMWFuY3AKLzdIWjZQcDR6TVRXbThtbStYNE5qdkp6Q0xTYTJWd1RISGtvWFEreXp6a01YUUV0ZzFUTXlFcTk2TG51RlpyTgpoeExkcFlOeTZHd2RXaGYzWERNN1VrZzVRM2ltOFQ5Ulk2bHNlRG1qd1NoUVcxeDlCYUhHYmhRZW0xa2R5OENrCkVIV0xQeEh0RkQ2ZXBiYWhQWWdGMWJZVVZjaE8vdS8wMUxCaUxUd2I0MEJINmo0UVdLRXFiVVVTd01Pc045V1gKQ1ZIYVltUXhTcnhQM2RSS043Vm95VTJGYWpjV3hScmhEdzB5UVEyQzdwdjF3NnMzWW9abVk3M2F0bzN5d29zSAp5bWQvNUtxL3dtZmhZSFFYcnJrd2hMdW1kd3dkMU5uVitOV2hkQUZKdTFvQk5yMjZ4MDNlY1lWUlB3MW1uV0dGCnhEZ0ZPMXJHYStmK0NtU2lXRGZSZW1RZHNKNU43VHdXSnQ0ZzJVY3NoRERHU254WGRmaWpjSnlXNW1LOGJYcFUKUjBEWnByTDB1bUhmOWZyc2ZSbG5QbWJnVUgrRnc1R3lublQ2b3dMSUFJaDFVc21tbGc0UmVJY0NFYTJyL2dvLwpQRTBaSWhEOFhVRFE5MFNJSUZHb1hRam51c1JudWV4RWlzTlZtSUREOTQzRzZMQ3E0RzhyVFdDUVhCRHpiei85CnRXS3BVSkV0MFhVdEFkWHc5Rm5wZlJ0RDJsN2F5aDh6OVgyRThwcCtmMjRCeG14cE1sUE5zZ1prZGtNVU9QN2sKUkZSOWJVVGRScnFWUmdIbHhGREJLeGU1ZVUraFJuQzJPMHJINUk4cGt4M0NZNEF6VEZKNjFYTU0xazhCQThqYQpQNnl6S0FaZlBqdDkrc2RVamJaRGJXWHR6UjF6R3JTVjFJU25yS1RjUndubHhLZ0FWV090eTBubDlKMjI2OXkyCkZzVVlQeC9LckNDalROL21kM2JXUWFDczg4QUttSjBmRWVzYlNNbFd0RmlaMFU2RmxPVFRlZnJJNkw4clUyYysKdS8zYnVLNEk4Q2ZUVjlBMzg4dlY2QmRXZWNPbERpN1ZRVUQxdDFMeDROZzN2NEFaVEY0RkVvQVFFUjBBNUUrQwpBbWh1c2NMcE9mUnhiNGwzRjY5S0VCY3BCM05RT3QrVUJjdERtclBsdUo2QXZkV05Bb0srUzlpSFBWK242T2ZJCnBGSUJrZG13V2lvMUlub3RKYi9XTUVFenZqNEt3a1dyQmdsUjVCOGNGc3NOY0U5WC95VWdaS1BtcncyMy9BeFQKYkVQbkRSSE5ibXU5TUpqZFAydjhjdlFvd1d3cHoySlI1UzljWEIrbHhYNDlNb0ZiRSs3UlUrbnZ0MXBMQnpPMgotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  tls.pw: ZWFzdC0xLXBhc3N3b3JkCg==
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZxekNDQTVPZ0F3SUJBZ0lVQVp5cmtDdy9WRkw2R1JRdHJHYXFnaUpJbzhVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdNQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIREFoQwpjbTl2YTJ4NWJqRVdNQlFHQTFVRUNnd05WSEoxYzNRZ1RXVWdTVzVqTGpFWE1CVUdBMVVFQXd3T1ZISjFjM1JsClpDNURRUzVqYjIwd0lCY05NVGt3T0RJeE1UWTFNREF6V2hnUE1qSTVNekEyTURReE5qVXdNRE5hTUdReEN6QUoKQmdOVkJBWVRBbFZUTVJFd0R3WURWUVFJREFoT1pYY2dXVzl5YXpFUk1BOEdBMVVFQnd3SVFuSnZiMnRzZVc0eApGakFVQmdOVkJBb01EVlJ5ZFhOMElFMWxJRWx1WXk0eEZ6QVZCZ05WQkFNTURsUnlkWE4wWldRdVEwRXVZMjl0Ck1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBckNOQ1ZWV1haN294V2t1enRRWVAKMWdxaDVUQjFZaysrTk0yUnlDQmtXc2d0aXdzWDNoaWtjRFdpMnB1aG04REJSL3FGKzZlVzhUa0s5eGl1bHBMZwphaFBXS1Zac0UyWFhzYVczMm9zTXVmanh4elFFNjVobUM1Ykw0NEpaejAxSFh4RU5rUUVDY3FxZFkyK3JncDVXCnpHdUVodFdjbVEzeG42OGNHR3U0VEErYXl0YjRXVGJzckRHTHVBMElVMnp5WXFVUXNJa1E1K2RXMC8rU0R2V1UKSytGZ3FOTkYrS3VMNnJyTHU4N1ZtdE1SN1ljMU9GdnhtNmo5dTBka0dBN3lpZHVPRkUvUE1saGUwOU9ZOUhGTApCYXY3QndCZXF0NzFCdng0M3pqNkdDbW1ZQVZuUTFGVk1sTk5rWjAyeVN1VzNDMXIzY2c1S04xV1Z3a2gvNWZwCmRwYnR6SDFGMmV4UVoyelZrajl5Z0greDhvUFJyczhOM0NBTld5cmVjdmhibnRCYzhrMW5vY1V5VVJ2Mm9JQysKWDRTVmREd0V6eU1tVW5UQ2JkMDlESnVwbzAzY0hTdjQ0d3Z3dFBSOFlrNng5Q3pYUW1lU1Y2ZE9NQkw0dFZCVQo1OWhqUFk0a0hJTTVpTTF6VEhYQkdRSHZZa3hIcW04ckFSR00xVXpxbU9pVFgzWENlTXNWNDBBVm1vWEM0cHlnClNQTTRTdklKTUlBMi9XTUgrQ1pCMTZ0V0Y3K2w4K1A0RXNRdGg1WjhyYXRhZHlTa3E3c0VqcjFhd3JFeWNXMXkKTWZUSnkwZm9IR1hobThvYW8yTlhOS2h4WUNXVFcyQzVpcE9ld3ZGUUZ3eklIOWsvWk5TL2V0WW9SeXVCWEwvVwpQVnBxMFBLVXRGRVNTdjU3andLM01rVUNBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQm9mejh5b0J2SnpvbFlNCjZYdWFrbC9wcnN4Zk1COEdBMVVkSXdRWU1CYUFGQm9mejh5b0J2SnpvbFlNNlh1YWtsL3Byc3hmTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFFUlZBQUZud25LdU9Db1o2V3BXUHY3VAphcEFUNE5CelRHbGkydHdROEhCdm1WRmxmTUI3YmhYWE5LSnRybXlHdXJ1MTlQNXYyUEs4aFhhRUNXUGwwWno5Clh4VzBiaklBUVBCNExUUFhOWHNiTy9vODY1OVpHYW5yYkhKMG5Rck1XMXNqV2F2anRTSTJ1TWZ4cnJkMitLSzIKK1g2OVZockg2NWZjdXlBUnU0R0UxWFVoZ3hTYjB6ellja01HMjk1anNRTEF6UjhzUWxNWUtRajJQY1hLNE1tMwpOb3FlUEErMWc0NlhaNkdzWkthcVpwbUFacks0ejVZWWorQnVucUhzUEQrUTlsNVpmTmY5Z1k2Q0VNa21uTHphClcrYnhFSmMxSHVsa2VWdjZ2UEpsNDJmemdEcVVTMkJ0MHluUyt5UlNxc01mY2dXVFJxWnY1TXVEbGdQK3NkWG8KSG9JVDBBdDB5SS9CY2EwdEszRUNIYlF4MmJFRHB4bWM3anNBbXdiL0Fhd2ZJcFRyV0c3M0h5UDhSNDlTQktWMQpMeExCZEhod1N5SVFDejBjNzB0WlFFaHcydWF3MURBcjBSWE5qbTMxbDBTTEpwQ05EczUyaHNGYkFsS1RaSnlyClZ5ZDhEcHJTSkZVTU1yUFQzKzhBUWZUQUtjekhleHQ0dzFsTmJ0T0s5dFp6ZXNjeGhHSS9ZdUtCUW9NVHB4eXEKT2FHNXg0L0NBa05TSDAxMi93bUxaT1NyeldEU2pSR3JoaDhWa0NLM0JtenJrTzArSjNGV2tWaTRWcnpiSjV2ZQpyUHBTWTV5Ylg5bnlSWm5RTjgwLy9iVnZEVEwzZjZsdkdYczZRSEJvMFhNc001T3VocFBnVWI2K0xVOWZvdnloCmsrM0ZtWkhSUjdaYklZTm9JeW5UCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: qdr-internal-cert
type: kubernetes.io/tls
---
apiVersion: v1
data:
  qdrouterd.conf: |
    router {
       id:east-1
       mode: interior
    }

    sslProfile {
       name:ssl-profile
       certFile: /etc/qpid-dispatch-certs/internal/tls.crt
       keyFile:/etc/qpid-dispatch-certs/internal/tls.key
       passwordFile: /etc/qpid-dispatch-certs/internal/tls.pw
       caCertFile: /etc/qpid-dispatch-certs/internal/ca.crt
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: amqp
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: 8672
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
       http: yes
    }

    connector {
       name: to_east-2
       host: inter-router.sku-mongo.apps.east-2.sysdeseng.com
       port: 443
       saslMechanisms: EXTERNAL
       sslProfile: ssl-profile
       verifyHostname: no
       role: inter-router
    }

    connector {
       name: to_west-2
       host: inter-router.sku-mongo.apps.west-2.sysdeseng.com
       port: 443
       saslMechanisms: EXTERNAL
       sslProfile: ssl-profile
       verifyHostname: no
       role: inter-router
    }

    address {
       prefix: closest
       distribution: closest
    } 

    address {
       prefix: multicast
       distribution: multicast
    }

kind: ConfigMap
metadata:
  name: qdr-config
---
apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: qdrouterd
spec:
  ports:
  - port: 5671
    name: amqps
  - port: 5672
    name: amqp
  - port: 8672
    name: console
  - port: 55672
    name: inter-router

  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdrouterd
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: qdrouterd
        image: quay.io/interconnectedcloud/qdrouterd:1.8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: qdrouterd
  name: console
  selfLink: /apis/route.openshift.io/v1/namespaces/hello/routes/console
spec:
  host: console.sku-mongo.apps.east-1.sysdeseng.com
  port:
    targetPort: console
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
---
