apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZkekNDQTE4Q0ZDZ0d3dHh0Q3VONGRiL2FKZ1Z0Ty9MUzZkM2hNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1HUXgKQ3pBSkJnTlZCQVlUQWxWVE1SRXdEd1lEVlFRSURBaE9aWGNnV1c5eWF6RVJNQThHQTFVRUJ3d0lRbkp2YjJ0cwplVzR4RmpBVUJnTlZCQW9NRFZSeWRYTjBJRTFsSUVsdVl5NHhGekFWQmdOVkJBTU1EbFJ5ZFhOMFpXUXVRMEV1ClkyOXRNQjRYRFRFNU1EZ3lNVEUyTlRBd00xb1hEVFEzTURFd05URTJOVEF3TTFvd2dZc3hDekFKQmdOVkJBWVQKQWxWVE1Rc3dDUVlEVlFRSURBSkRRVEVXTUJRR0ExVUVCd3dOVTJGdUlFWnlZVzVqYVhOamJ6RVZNQk1HQTFVRQpDZ3dNVW1Wa0lFaGhkQ0JKYm1NdU1VQXdQZ1lEVlFRREREZHBiblJsY2kxeWIzVjBaWEl0WkdWdGJ6SXRZVzF4CkxtRndjSE11YzNWdGJXbDBMbk41YzJSbGMyVnVaeTEzWlhOMExUSXVZMjl0TUlJQ0lqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBd21rWWFZak5lZE1MMGNjSnl2MU5URC9ScklubTZJUitldTVKZzhhbgpvWW0rSE8vbTRMU3dTMzdrdFNlK2M2Yng5djJPWTZRRW1rcmRRdVhGMEZhZitxandla21kNDNXZFNPN0ZQVXNzCjBueXBPUHhPekdjY3VhTVJEZVc5bWtCTEdkcDFseVJXSXhua1lSTHJocVVrNTJDRkxZZ3FhNm0xUms3SVBPQ3oKNHppZlkrcUY1SDRLMWVGbkphM1MvRHpRZTBkSG1kQnhPNGwvWHh3V1NDQUQxckwreXBGSVRmM3BBS1N4SlY3aApibHJkM09ZaXhZZHQ0R3JTeFVpcENJUEk4VjNCejlleldRNDhKMWdsS3ZCaHJoU204UU5DRm1aQU9NdGhmbUtLCkJka1VMWW1BTzgzOFVBTmlQUUs4TGd6SUpyNjZBVDl1L1NNZEJITDdmcEZ6Qm1nbkpSeWhJcVlGSE42aXpWbzMKci9aRkN2T1FrL3NRbVNjeERGT0VsMEhJSExQUnBJOWdrTUhWRExaWElTd05QbmkzcldQK3FVVE9mM3lOczNyeQpjb2hEZ3h2R1RMRXkzQnlHVmkxVDR6SlprTkxkVEpESjhRVUFzQitBcFA3T2RoUmJKZTNwY081Y2NIZ2dvc0YrClBZWW1yUjZuUWhRVGo2a2YwblZETDNITjVHYjcrUmtEZVduRVpQSHRMRWxPSUVPaTlVeUhZY2s1SUgxK3RjUlEKRnl2Qisva3BaMFlOTTh6NEhVZkdmSEw3WkhSNW9nR0RjVkx3QXMwSklvM3VMZmVzb01tckhLNjVVemFJSGFJZApmSFVOYlBEd0xoNGtqbnJZTVZGUFh2Ni9tMFd4RjRMc0ZaMittalU2RE9nMENEQXppNXhNNXc2RXFXS2hpcEROClR6Y0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQWdFQVVCbmsyQVZmQVMrREFpM3Z3MThrTHk3MTFsN1EKc2o1T0dUSmdadFVYaHJONlhyMUtpWmNZZ2lRNGdGNFA0eitzcnhFc0RQL2RUUWJ0ZVcvMEpMZm1Ld21BQzdodwpYbHRTSTlOdHZvNHVUMTFGbm1IWG1tbnNKZ3I0K2tlZThyci9QTEEvdkg0blh4MmNBT3B3Tnl4ZWdlN3lCOVBtClNPQUtOSXExeFF2NkFvSnVlN0ZuMTVaRWpqSDROZnZNRFR1ejBHcDFRQTdsSVdIZnE0TVBQL2txSTlMUHBvSXcKVDlOVHI0Qy9OUENJRElnVk1OZzlpVFVCaEpJcFpUcTNhMXZ4Yk9TV2I0TkZ4RUNGM25SZUZ1dURBa01GOENNVwpLeitJWklRZTkzTysxVXBrN29VV0kraGdUTkdlSXBud1RuQUdHWU5oOFEzK2txa3JsZG5TVnFDcXVKYlQ3T0ZTCmdyOGpSVWVrUHJKeHhjb1I1Uks1YnhFNXFHNlA2b29YRGYvTUJoblh0VmZTSGpXZUF2Z3dISVIyMTdRZjl3VkYKdy9qcFQ5WjlFRUlGQnFYb2lFZnRJZEFJSnFnRG5ZOU5CQ0VManFlMzVHc3N1Z0VTQ0dUektQTC9yM3ZlT3ZnVQpqTm1PVlBmSVpYYXF3ZHFLVHZ6WGxjQnNwUmRqSUp4c0I4RnlCNkN4ZnpnaE9wTm5DMi9xWXBMWXVyanJiRUd3CitzVWloU01kQXpic08xenhSbUdmU3ZXWnFWMWtqQnVCRTdhNU1VWVp5Q3NCZUtDSDZRVkNFNUEwRWNZV3NBYW8KYTNTdXZJZDFlWVA3R3BnUk9Qd050ZUVkUUhUQWd6VW9ock5mQU1nSnBwVzRLQ1FOTWRpYlNmaGJIQVRBUmFpNQplY1FobVhDWmZ2dHhqQ3c9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpQcm9jLVR5cGU6IDQsRU5DUllQVEVECkRFSy1JbmZvOiBBRVMtMjU2LUNCQywwMzk0QUEyNTc4MTgwRUE4RTZDRTZCRTRERTg4OENERQoKOE16dkJ1alZTamZaU2pnWGFxL29nYmdSMDB5Y09mTTFQc2FCSkVTaDJsRHVYVVc5QmFrYnY4eGtUWTlEemNrNQpYdDVmU2N1TmNlL0hWMzdKVCtRT1lCNnNZM1FwMEtmeVNQNVcxdm5rWG1OL2hlUEdQMTFoVTRpY1hPbzg3OEFYClYydzBVVTE4US9RMUJZK0RsUkRNQ3BZbEFBZU1IUWlYV0hKdWFSSSt5cmhjOUVaeTZIQWhwZHNFL3pJSVU3Q2MKVEFtOUVLWVpWcW1rWEdEcjFoeEZxNEZrTlJWNmdFcWVEVEQ4N2tOQmVPbDZKWmpuYlFmRENGTTE0TUR6RU1QUApKQXhuRHNnWk03VWtMcmpFcHFxVzQxMStIVVZvVlhjb1hRaDdVV2gyc3VTK2xHYStQNnJCblpiZzJwVEJEeUZ5Cm05cCtvMmNIVW91VStCZHdqWUlqU1VYTmRMUjRwb2htQlJhaWN4Y0VMT3RRR09jWVJzSFl3Mm5rUEw4V3o2R1kKOE9JUWl4ZEhkb1U5cUh2ckwvSThZU0VXSDUraURIcE1UZ0JpRExEYTlTU1Z0Q3lIc1JTT1BJNHVkSVk0QzU3QgpNYzJzZno4WGhqUWRYdS9QdXRKc09INmcxcVlGU1VTTlJZeDBvVFVRS3Vsd2hRU2VaZnNkM2hJaCs5c3FFcHhMCm1xcmo4QzB6aWhxSXhXUmd1SnI4Q1VMWG9Lak9jNUs2VTJNMXgwd3RhNkZTQnNzQ2twMW1zTGFDMHJUZHBlRTQKTEpTRklxTCttd1NTalcvWkJQRU9pVGpiaXRTRnlLSCs5WU1ySXl2dXJwSnRZNWY5Q1BYVW1OM0l4akkzSi8rdwpDV0JpQ21XNmR5dmFrTS82UENjOERMVlF5QXlybG1BNmJqVFFPdkZEaFU4Q0YzdDZLWXhSaGxDQlY2Z0hxMDZ5Ci9wd2pRSXU5VmRRUS80TS9OZThqL09FTm5ram9RRTgzWlQ3NWZzNHRlNjQyUkxieFZrdzNwS0lxOEM1UEdNdkMKNGQzNUtoSWJLUE9qV1N4dVJndis3ZWMzQjBIWWdneTNBOFEyTmFGQ3hqbEZDNUQ1MW4vWU1KRHJoWDZZRkJ0aApucVNPaXIxelhOOGhSTWtObm00SlpGZklzeWtiU3BtTVBVcEc3bXM0SmVmMWJlU0w3RWVQb0lQSzR6TmIxOU1vClQzWk8yOW55RXBBMEQzbEdUSTFZVUI0dGRnK1dWc3VTNGx6cjhjVzVGTngzeWdtVnEyaDlVaTlTN1A2R1ZuRTMKWmw5VGRmYm16NVpsR1gzTXE1dGpSYXFxWUV1blNFMVZpcTdUTHJsN3lBYzNFT0c5dWVzNElhR2xOUVVEbkY5dgozL2ZsaXZmSG94RGVtZUpJOHlXSFdrV3lqNEtzVmVrZGdzNDNTR2xuNVc2blRIeVdET1d3TUpyNSswaEFmOWdSCk1Ra05KZmF4cGx5emdVMHp1RlozdWc3SmR6OUo2VlhRSXVDS1BXZW9ITExkRHVjNDRRWSs0NURXb1E1UUVPczQKd1l6UktMRFdEU3RMQzZkTTk1MUVpWWZFMXQ3dVM3WlBCOFNYZzNnZE4vdXFubHVQb3dWWG1KUkFuTExSNXBCYQpDRmYxKyt3ZUtzODNXR003SFlrM2hEcDkzb2pLc2Jza3FBVUhqdHRZcEJrdU9ZTk83YS9ycDJxUVVwancvSXFtCmYvY3BWb3RHZjZ1dnljcW5yeWpxcm5uYXV0V3lxWGxvbG5rTjVIck5oc29NRzhqZExLa1hyWmI0UkJnZDNFL2MKRHB0T21rNGRHYWNpRUxsZmQwZjNmQnlha1dZNUNkdld5clE5SFo5YWFlY1NUanVOMnFCVUxCbzVGWklXeDlSRApISXN1Z1d6c3RLdzNoLzNwNFBoM1dJTEN6MWxaYXpQMHMvdWdsMUJkbGZXYlF6eGNHU0tUQ0ZabWh4UXNKajRkCnR4U3RLTzFMMjRhUjV3VXh6K0JqNjVxckFCYzVzcmdjTTFCcHdUbkl6eDZJWXlYdmpTdlN5T1dCWjZsZEx6L28KbGNCc0FRbFg0Sm41TWZkdVlrdGp2ODhMR2p4OUhVand2RDA2b3UyMjh4TW4rYkk2VXBZUzU0elpTR1VHWFp5ZwpaK0RGQ3pJTGFkSm5uUG1wZmZtN045bCtqbmgvRmFmK3RGVlAwZjh6NThxS2RvemxPU3YyamU0RDBJaDJreElQCm5VUS9KbVFqL0ZLNTcyempleHV0b2lDZVhnN094a3NtVk43Q3RNV2pRTzRUL1dMT2k4VkpOdmVGb0ljMU91TTIKNzdSallIazBaaUtET1ZYMUt2OFNrZHBaQmJFNUxZMHVrOENlQTg5eldEc3Z3bFllSnlRRFBlSnhpWUZha0JBSgpPT1NrSmJucldENDZmVFpoSUE1ZzVkT2oydkh1QmlyejN4SzNuNEpkZXVUNHF4cEdERkpHMDlTVmdMcU9rSysrCmhyUlZqa0s0N2VKNUFZMVBDbmF0cTZTcHpoQkpzUGFMN2l0Q3U2ZGYzNFFIMkEwY29FSjRzekZudDNucXZxL2sKYUp5eHBwdnNSTkNQbXI1Qld5Uzh2VUpINi9tWUdtaXAxaGUxZTEwcTEyT2ZjYnF5K21EaHBhaFVxb3kvNVo0NQpoYTgyd1E5RmZlcWtKVnJMaDhLOHpKY1hSU1g0UUJ3MlhUejRqYk8veml0K3cwM2g1cG1IZGI4Ty9qL3N0NnZOClRuY1BFZFhQaGtqbzBYbFhxUitVUVY4cmVJVFNtZEtiaTZUYUo2elJOSEZZRjJsSW5VdDR0NkoycmpwYVB0V2QKTzAvOGQ5TzYxb2t6bGRVTTRqbmJON0hCbGI4aU5hTzJpVXkyZ0ZTbXpCVnNQdlVWdm9jSm1iZmdzamRjRGFaVgptWFBRZ0VsNHdUbDg1NWMxRFBEdXpLZmpVcnc0ZExyQ1ZTalBpclhDUWI4blFtSzB3Z280TFlSbUFpdXdWeDYwCjBHc09ldkM5Z0djdUpTZVVGZ0ZTbklnVkxWNkgvcVUrZWZtWTZUMUxOWGlXbTFLMFVqMngzYVByeWEzOVhDaTUKUnFORmVCbk9YS2pHdWZxVUZGZDJwcGpIUGRaeWdFK21kQk5FZnVBOEQwSHp6TWExbEl0ZytINjZOdXo3SDZDWQp2dEttdmlESWE0N0pXMnZjVHdwRHAwUllhZmdnUkgxUHNwRTNaKzRVNkxGZGQ5bmFTd081T1orZ1pqNGYzeS9WCmZENUc1RzJ2V28wTFE1OSs5dzBGTkJwSzIrcjh1bVl6SnJhQmFTTnhoZ25XQk0vUUdrUFVROGZqME1yVHFoK2kKbG1OakpuZUJWb0ZMLzlENXlWMVA0UFNsRVIvbnpoLzkyUEUzdkhnb2RLQlhqRzR2K0twaStuY1M1ZldTSmhYYQpCQkFmUStxNWVjU3ZjOEppZzhPV1FndTFFa1lvTXZlcEw3UHVzS2lNY0FyVDl1TVQ3MEV5VDR6RHdBSU15YnljCko1WnlZak93WVN0VG5SN1R1bHJicTkzUE5xWnhkL3lIZGxjbzFoVzNTV2NVUjhvcFUrUkxJdE5UTWozYldmd0oKSzFuR3F1M3FRZWh0L2hrWFk1RG51dFhGakhBQlhseWlydC95aG9vcUNiK3ZkYkU5YmdCSHB3SDhzS01BSmE3OApzTlg3dVFvZWhSaDROWnk4M3k1QlBUM1IxaW1JZ3cxUk4xQTVmQ1Fhd2dtamtqeTd5V0pZZzZkdTdpR2FXZk53CnYralphRjBBVFA3V0NVVnl3dElMRTlhc2hZR2M3N1JHYWFibEJWVkhhOGZwM0RaYzdLSXlHNFN3TXhHZEg1U2EKVElJN0tJd21wTDhJNVZia0FySmhPczNibXNETXYyclB6dEFTY1JHaVZXbEZyQm5FQzNQRzFMOWt2Y0txbDJoSQovMGtGWDFrTGd3anFRTFJBbjFQZHZzQ0FxeXVLbWR0N2FCdStET2srTnBzZTFJQno0c0tndWNmcGlTWGpteFk4Cld1dXBYZFZFSzdTbUZTc0R5R1NzKytVRVhCS0kwenNTZXQ5N1dYOEh2eWRuQ253Tk5PcEdyWDJXbFgxRTF3ZWQKL29KYVJjYWFLMXorVkpDOFVPNDdVNFRiOGdtVlh0WENpWk1CUnR3OEdmbUYwRmxxZE8rM0RWR2RFeE9OcHd3egotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  tls.pw: d2VzdC0yLXBhc3N3b3JkCg==
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZxekNDQTVPZ0F3SUJBZ0lVQVp5cmtDdy9WRkw2R1JRdHJHYXFnaUpJbzhVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1pERUxNQWtHQTFVRUJoTUNWVk14RVRBUEJnTlZCQWdNQ0U1bGR5QlpiM0pyTVJFd0R3WURWUVFIREFoQwpjbTl2YTJ4NWJqRVdNQlFHQTFVRUNnd05WSEoxYzNRZ1RXVWdTVzVqTGpFWE1CVUdBMVVFQXd3T1ZISjFjM1JsClpDNURRUzVqYjIwd0lCY05NVGt3T0RJeE1UWTFNREF6V2hnUE1qSTVNekEyTURReE5qVXdNRE5hTUdReEN6QUoKQmdOVkJBWVRBbFZUTVJFd0R3WURWUVFJREFoT1pYY2dXVzl5YXpFUk1BOEdBMVVFQnd3SVFuSnZiMnRzZVc0eApGakFVQmdOVkJBb01EVlJ5ZFhOMElFMWxJRWx1WXk0eEZ6QVZCZ05WQkFNTURsUnlkWE4wWldRdVEwRXVZMjl0Ck1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBckNOQ1ZWV1haN294V2t1enRRWVAKMWdxaDVUQjFZaysrTk0yUnlDQmtXc2d0aXdzWDNoaWtjRFdpMnB1aG04REJSL3FGKzZlVzhUa0s5eGl1bHBMZwphaFBXS1Zac0UyWFhzYVczMm9zTXVmanh4elFFNjVobUM1Ykw0NEpaejAxSFh4RU5rUUVDY3FxZFkyK3JncDVXCnpHdUVodFdjbVEzeG42OGNHR3U0VEErYXl0YjRXVGJzckRHTHVBMElVMnp5WXFVUXNJa1E1K2RXMC8rU0R2V1UKSytGZ3FOTkYrS3VMNnJyTHU4N1ZtdE1SN1ljMU9GdnhtNmo5dTBka0dBN3lpZHVPRkUvUE1saGUwOU9ZOUhGTApCYXY3QndCZXF0NzFCdng0M3pqNkdDbW1ZQVZuUTFGVk1sTk5rWjAyeVN1VzNDMXIzY2c1S04xV1Z3a2gvNWZwCmRwYnR6SDFGMmV4UVoyelZrajl5Z0greDhvUFJyczhOM0NBTld5cmVjdmhibnRCYzhrMW5vY1V5VVJ2Mm9JQysKWDRTVmREd0V6eU1tVW5UQ2JkMDlESnVwbzAzY0hTdjQ0d3Z3dFBSOFlrNng5Q3pYUW1lU1Y2ZE9NQkw0dFZCVQo1OWhqUFk0a0hJTTVpTTF6VEhYQkdRSHZZa3hIcW04ckFSR00xVXpxbU9pVFgzWENlTXNWNDBBVm1vWEM0cHlnClNQTTRTdklKTUlBMi9XTUgrQ1pCMTZ0V0Y3K2w4K1A0RXNRdGg1WjhyYXRhZHlTa3E3c0VqcjFhd3JFeWNXMXkKTWZUSnkwZm9IR1hobThvYW8yTlhOS2h4WUNXVFcyQzVpcE9ld3ZGUUZ3eklIOWsvWk5TL2V0WW9SeXVCWEwvVwpQVnBxMFBLVXRGRVNTdjU3andLM01rVUNBd0VBQWFOVE1GRXdIUVlEVlIwT0JCWUVGQm9mejh5b0J2SnpvbFlNCjZYdWFrbC9wcnN4Zk1COEdBMVVkSXdRWU1CYUFGQm9mejh5b0J2SnpvbFlNNlh1YWtsL3Byc3hmTUE4R0ExVWQKRXdFQi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFFUlZBQUZud25LdU9Db1o2V3BXUHY3VAphcEFUNE5CelRHbGkydHdROEhCdm1WRmxmTUI3YmhYWE5LSnRybXlHdXJ1MTlQNXYyUEs4aFhhRUNXUGwwWno5Clh4VzBiaklBUVBCNExUUFhOWHNiTy9vODY1OVpHYW5yYkhKMG5Rck1XMXNqV2F2anRTSTJ1TWZ4cnJkMitLSzIKK1g2OVZockg2NWZjdXlBUnU0R0UxWFVoZ3hTYjB6ellja01HMjk1anNRTEF6UjhzUWxNWUtRajJQY1hLNE1tMwpOb3FlUEErMWc0NlhaNkdzWkthcVpwbUFacks0ejVZWWorQnVucUhzUEQrUTlsNVpmTmY5Z1k2Q0VNa21uTHphClcrYnhFSmMxSHVsa2VWdjZ2UEpsNDJmemdEcVVTMkJ0MHluUyt5UlNxc01mY2dXVFJxWnY1TXVEbGdQK3NkWG8KSG9JVDBBdDB5SS9CY2EwdEszRUNIYlF4MmJFRHB4bWM3anNBbXdiL0Fhd2ZJcFRyV0c3M0h5UDhSNDlTQktWMQpMeExCZEhod1N5SVFDejBjNzB0WlFFaHcydWF3MURBcjBSWE5qbTMxbDBTTEpwQ05EczUyaHNGYkFsS1RaSnlyClZ5ZDhEcHJTSkZVTU1yUFQzKzhBUWZUQUtjekhleHQ0dzFsTmJ0T0s5dFp6ZXNjeGhHSS9ZdUtCUW9NVHB4eXEKT2FHNXg0L0NBa05TSDAxMi93bUxaT1NyeldEU2pSR3JoaDhWa0NLM0JtenJrTzArSjNGV2tWaTRWcnpiSjV2ZQpyUHBTWTV5Ylg5bnlSWm5RTjgwLy9iVnZEVEwzZjZsdkdYczZRSEJvMFhNc001T3VocFBnVWI2K0xVOWZvdnloCmsrM0ZtWkhSUjdaYklZTm9JeW5UCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
kind: Secret
metadata:
  name: qdr-internal-cert
type: kubernetes.io/tls
---
apiVersion: v1
data:
  qdrouterd.conf: |
    router {
       id:west-2
       mode: interior
    }

    sslProfile {
       name:ssl-profile
       certFile: /etc/qpid-dispatch-certs/internal/tls.crt
       keyFile:/etc/qpid-dispatch-certs/internal/tls.key
       passwordFile: /etc/qpid-dispatch-certs/internal/tls.pw
       caCertFile: /etc/qpid-dispatch-certs/internal/ca.crt
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: amqp
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
    }

    listener {
       role: normal
       host: 0.0.0.0
       port: 8672
       saslMechanisms: ANONYMOUS
       authenticatePeer:no
       http: yes
    }

    listener {
       sslProfile: ssl-profile
       role: inter-router
       host: 0.0.0.0
       port: 55672
       saslMechanisms: EXTERNAL
       authenticatePeer:yes
    }

    address {
       prefix: closest
       distribution: closest
    } 

    address {
       prefix: multicast
       distribution: multicast
    }

kind: ConfigMap
metadata:
  name: qdr-config
---
apiVersion: v1
kind: Service
metadata:
  name: messaging
  labels:
    app: qdrouterd
spec:
  ports:
  - port: 5671
    name: amqps
  - port: 5672
    name: amqp
  - port: 8672
    name: console
  - port: 55672
    name: inter-router

  selector:
    type: qdrouterd
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qdrouterd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qdrouterd
        version: v1
        type: qdrouterd
    spec:
      containers:
      - name: qdrouterd
        image: quay.io/interconnectedcloud/qdrouterd:1.8.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5672
          protocol: TCP
        volumeMounts:
        - name: qdr-config
          mountPath: /etc/qpid-dispatch
        - name: internal-certs
          readOnly: true
          mountPath: /etc/qpid-dispatch-certs/internal
      volumes:
      - name: qdr-config
        configMap:
          name: qdr-config
      - name: internal-certs
        secret:
          secretName: qdr-internal-cert
---
apiVersion: v1
kind: Route
metadata:
  name: amqps
spec:
  host: inter-router.sku-mongo.apps.west-2.sysdeseng.com
  port:
    targetPort: inter-router
  tls:
    termination: passthrough
  to:
    kind: Service
    name: messaging
    weight: 100
  wildcardPolicy: None
---
